#!/usr/bin/python
import csv
import sys

if (len(sys.argv) < 2):
    print "usage: convert_db [filename to convert]"
    sys.exit()

fname = sys.argv[1]
oname = 'tweetdb'
cfile = open(fname,'rb')
reader = csv.reader(cfile)  # creates the reader object
ofile = open(oname,'w')
for row in reader:   # iterates the rows of the file in orders
    if (row[2] == "" and row[6] == "" and "@" not in row[5] and "#" not in row[5]
            and "&" not in row[5]): 
        
        text = row[5]
        text += "\n"
        print text    #prints each row
        ofile.write(text)
